#include "../sein.hpp"

int main(void)
{
    // doc_create_new_config(path, usage_async) //
    // usage_async=true stores the flag for future async saves //
    auto doc = fd::sein::doc_create_new_config("./configCPP.sein");

    fd::sein::doc_add_header_comment(doc, "Auto-generated by SEIN Writer");
    fd::sein::doc_add_blank_line(doc);

    fd::sein::doc_add_include(doc, "colors.sein");
    fd::sein::doc_add_blank_line(doc);

    fd::sein::doc_add_global_var(doc, "APP_NAME", "My App");
    fd::sein::doc_add_global_var(doc, "VERSION",  "1.0.0");

    fd::sein::doc_add_section(doc, "Window", "main window settings");
    fd::sein::doc_add_value  (doc, "Window", "title",  "${APP_NAME}");
    fd::sein::doc_add_value  (doc, "Window", "width",  "1280", "pixels");
    fd::sein::doc_add_value  (doc, "Window", "height", "720",  "pixels");

    // Demonstrate referencing a system env variable in a value //
    // ${SYSENV:HOME} will be expanded when the saved file is parsed later //
    fd::sein::doc_add_section(doc, "Paths");
    fd::sein::doc_add_value  (doc, "Paths", "config_dir", "${SYSENV:HOME}/.config/myapp");

    // Section inheritance is a parse-time feature - just write the header //
    fd::sein::doc_add_section(doc, "Character");
    fd::sein::doc_add_value  (doc, "Character", "health", "100");
    fd::sein::doc_add_value  (doc, "Character", "speed",  "5.0");

    // Note: inheritance syntax [Player : [Character]] is written manually //
    // because it is a parse-time directive, not a writer concept //

    fd::sein::doc_save_config(doc);
    return 0;
}
