#define SEIN_IMPLEMENTATION
#include "../sein.h"

int main(void)
{
    // create_new_config(path, usage_async) //
    //   usage_async=true stores the flag for future async saves //
    SeinDocument *doc = sein_doc_create_new_config("./configC.sein", false);
    if (!doc) return 1;

    sein_doc_add_comment(doc, "Auto-generated by SEIN Writer");
    sein_doc_add_blank  (doc);

    sein_doc_add_include   (doc, "colors.sein", NULL);
    sein_doc_add_blank     (doc);

    sein_doc_add_global_var(doc, "APP_NAME", "My App",  NULL);
    sein_doc_add_global_var(doc, "VERSION",  "1.0.0",   NULL);

    sein_doc_add_section(doc, "Window", "main window settings");
    sein_doc_add_value  (doc, "Window", "title",  "${APP_NAME}", NULL);
    sein_doc_add_value  (doc, "Window", "width",  "1280",        "pixels");
    sein_doc_add_value  (doc, "Window", "height", "720",         "pixels");

    // Demonstrate referencing a system env variable in a value //
    //   ${SYSENV:HOME} will be expanded when the saved file is parsed later //
    sein_doc_add_section(doc, "Paths", NULL);
    sein_doc_add_value  (doc, "Paths", "config_dir",
                         "${SYSENV:HOME}/.config/myapp", NULL);

    // Section inheritance is a parse-time feature - just write the header //
    sein_doc_add_section(doc, "Character", NULL);
    sein_doc_add_value  (doc, "Character", "health", "100", NULL);
    sein_doc_add_value  (doc, "Character", "speed",  "5.0", NULL);

    sein_doc_save(doc);
    sein_doc_free(doc);
    return 0;
}
