import sys
sys.path.insert(0, '..')
import sein

# create_new_config(path, usage_async) #
# usage_async=True stores the flag for future async saves #
doc = sein.create_new_config("./configPY.sein", usage_async=False)

sein.add_header_comment(doc, "Auto-generated by SEIN Writer")
sein.add_blank_line(doc)

sein.add_include(doc, "colors.sein")
sein.add_blank_line(doc)

sein.add_global_var(doc, "APP_NAME", "My App")
sein.add_global_var(doc, "VERSION",  "1.0.0")

sein.add_section(doc, "Window", "main window settings")
sein.add_value  (doc, "Window", "title",  "${APP_NAME}")
sein.add_value  (doc, "Window", "width",  "1280", "pixels")
sein.add_value  (doc, "Window", "height", "720",  "pixels")

# Demonstrate referencing a system env variable in a value #
# ${SYSENV:HOME} will be expanded when the saved file is parsed later #
sein.add_section(doc, "Paths")
sein.add_value  (doc, "Paths", "config_dir", "${SYSENV:HOME}/.config/myapp")

# Section inheritance is a parse-time feature - just write the header #
sein.add_section(doc, "Character")
sein.add_value  (doc, "Character", "health", "100")
sein.add_value  (doc, "Character", "speed",  "5.0")

sein.save_config(doc)
