#include "doctest.h"
#include "../sein.hpp"
#include <cstdio>

TEST_SUITE("writer api") {
    TEST_CASE("create and save document") {
        auto doc = fd::sein::doc_create_new_config("test_output.sein");

        fd::sein::doc_add_header_comment(doc, "test config generated by SEIN Writer");
        fd::sein::doc_add_global_var(doc, "VERSION", "1.0.0");
        fd::sein::doc_add_include(doc, "theme.sein");

        fd::sein::doc_add_section(doc, "Player");
        fd::sein::doc_add_value(doc, "Player", "health", "100", "starting health");
        fd::sein::doc_add_value(doc, "Player", "speed", "7.5");

        fd::sein::doc_add_subkey_value(doc, "Player", "position", "x", "100");
        fd::sein::doc_add_subkey_value(doc, "Player", "position", "y", "200");

        bool saved = fd::sein::doc_save_config(doc);
        CHECK(saved);

        FILE* f = fopen("test_output.sein", "r");
        CHECK(f != nullptr);
        if (f) fclose(f);

        std::remove("test_output.sein");
    }
}